# Generated by Django 4.0 on 2022-01-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=40)),
                ('felhasznalo_nev', models.CharField(blank=True, max_length=20, unique=True)),
                ('szervezeti_egyseg', models.CharField(blank=True, max_length=50)),
                ('szoba_szam', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vonalkod', models.CharField(max_length=10, unique=True)),
                ('gyari_szam', models.CharField(blank=True, max_length=20)),
                ('gep_szam', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('megnevezes', models.CharField(max_length=20)),
                ('egyeb', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
    ]
